name: "Extract Angular i18n Translations Action"
description: "Parses TypeScript and HTML files in an Angular repository to extract Angular i18n translation keys and values"
author: "Tomas Corral Casas"

inputs:
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  TENOR_TOKEN:
    description: "Tenor API Token"
    required: true
  DIRECTORY_PATH:
    description: "Directory path to look for i18n translations"
    required: true
  DEFAULT_LOCALE:
    description: "Default language code following ISO 639-1 standard"
    required: true
  OTHER_LOCALES:
    description: "Comma-separated list of other language codes following ISO 639-1"

runs:
  using: "node20"
  main: "dist/index.js"